services:
  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REGULAR_USER: ${REGULAR_USER}
      REGULAR_PASSWORD: ${REGULAR_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
      # /home/ewehl/data/mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_ADMIN_USER: ${ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${EMAIL}
      REGULAR_USER: ${REGULAR_USER}
      REGULAR_PASSWORD: ${REGULAR_PASSWORD}
      REGULAR_EMAIL: ${REGULAR_EMAIL}
    volumes:
      - wordpress:/var/www/html
      # - /home/ewehl/data/wordpress:/var/www/html
      # - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - 9000
    networks:
      - inception-network
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception-network
    volumes:
      - wordpress:/var/www/html
      # - /home/ewehl/data/wordpress:/var/www/html
      # - wordpress:/var/www/html


volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ewehl/Documents/Core/Inception/srcs/requirements/data/mariadb
    #   device: /home/ewehl/data/mariadb # Voor de vm
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/ewehl/Documents/Core/Inception/srcs/requirements/data/wordpress
    #   device: /home/ewehl/data/mariadb # Voor de vm

networks:
  inception-network:
    driver: bridge

