services:
  mariadb:
    build:
      context: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REGULAR_USER: ${REGULAR_USER}
      REGULAR_PASSWORD: ${REGULAR_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      # - /Users/ewehl/Documents/Core/Inception/srcs/requirements/mariadb
      # /home/ewehl/data/mariadb:/var/lib/mysql
    networks:
      - inception-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  wordpress:
    build:
      context: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_ADMIN_USER: ${ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${EMAIL}
      REGULAR_USER: ${REGULAR_USER}
      REGULAR_PASSWORD: ${REGULAR_PASSWORD}
      REGULAR_EMAIL: ${REGULAR_EMAIL}
    volumes:
      - wordpress-data:/var/www/html
      #/home/ewehl/data/wordpress-data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - 9000
    networks:
      - inception-network
    restart: always
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    #   wordpress:
    #     condition: service_healthy
    networks:
      - inception-network
    volumes:
      - wordpress-data:/var/www/html


volumes:
  mariadb-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/ewehl/data/mariadb # Voor de vm
    #   device: /Users/ewehl/Documents/Core/Inception/srcs/requirements/mariadb
    #   o: bind
  wordpress-data:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/ewehl/data/mariadb # Voor de vm
    #   device: /Users/ewehl/Documents/Core/Inception/srcs/requirements/mariadb
    #   o: bind

networks:
  inception-network:

